# Generated by Django 3.2.10 on 2021-12-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_auto_20211211_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='movielist.streamplatform'),
            preserve_default=False,
        ),
    ]
